apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
  annotations:
    description: "Nginx  pod for learning purpose"
spec:
  containers:
    - image: nginx
      name: nginx-container
      ports:
        - containerPort: 80
