services:
  notebooks:
    build:
      context: .
      dockerfile: docker/local/node/Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ".env/.env"
    environment:
      - PORT=80
      - DB_URL=mongodb://nb_user:nb_pwd@notebook-db/notebook_db
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - notebook-net
    depends_on:
      - notebook-db

  notebook-db:
    image: mongo:7.0 #
    ports:
      - "27018:27017"

    env_file:
      - ".env/.env"
    volumes:
      - type: volume
        source: notebook-data
        target: /data/db
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
    networks:
      - notebook-net

volumes:
  notebook-data:
networks:
  notebook-net:
